name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: macos-latest
            libcxx: libc++
          - os: ubuntu-latest
            libcxx: libstdc++11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v1

      - name: Install conan
        run: |
          python -m pip install --upgrade pip
          pip install conan==2.0.10
          conan profile detect

      - uses: actions/checkout@v2

      - name: conan
        run: |
          conan install ${{ github.workspace }} --output-folder=build -s build_type=${{ env.BUILD_TYPE }} --build=missing

      - name: CMake configure
        run:
          cmake --preset ${{ contains(matrix.os, 'windows') && 'conan-default' || 'conan-release' }}

      - name: build
        run:
          cmake --build ${{github.workspace}}/build -j4 --config ${{env.BUILD_TYPE}}

      - name: test
        working-directory: ${{ github.workspace }}/build
        run:
          ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
